sudo: required

services:
        - docker

before_install:
        - docker build -t gaurav0205/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true gaurav0205/docker-react npm run test
