version: "0.1"
services: 
        web:
           build:   
                dockerfile: Dockerfile.dev
           ports:
                - "3000:3000"
           volumes:
                - /app/node_modules 
                - .:/app
